# travis.yml for testing radare2. Initially written in 2014, by jn__.

os:
  - linux
  - osx

language: c

compiler:
  - gcc
  - clang

matrix:
  exclude:
      - os: osx
        compiler: gcc

sudo: false

addons:
  apt:
    packages:
      - dc
      - binutils
      - cabextract
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

cache:
  - ccache
  - apt

script:
  - git clone --depth 1 `doc/repo REGRESSIONS`
  - ./configure --prefix=`pwd`/install > /dev/null
  - make -s -j2 > /dev/null
  - make install > /dev/null
  - export PKG_CONFIG_PATH=${TRAVIS_BUILD_DIR}/pkgcfg:${PKG_CONFIG_PATH}
  - export PATH=${TRAVIS_BUILD_DIR}/install/bin:${PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib:${LD_LIBRARY_PATH}
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then mkdir -p /tmp/kcov && pushd /tmp/kcov; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then  mkdir ${TRAVIS_BUILD_DIR}/kcov; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && popd; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export KCOV="/tmp/kcov/kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID ${TRAVIS_BUILD_DIR}/kcov"; fi
  - export NOOK=1
  - export NOREPORT=1
  - cd radare2-regressions
  - VERBOSE=1 make -k all
  - make unit_tests

notifications:
  irc: "chat.freenode.net#radare"
  on_success: never
  on_failure: always
